# Generated by Django 6.0.7 on 2026-08-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_interview_postulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='decision',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('avanza', 'Avanza a la siguiente etapa'), ('no_avanza', 'No avanza')], default='pendiente', max_length=10),
        ),
    ]
