# Generated by Django 6.0.7 on 2026-08-10 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(blank=True, choices=[('dni', 'DNI'), ('ce', 'Carné de Extranjería'), ('pasaporte', 'Pasaporte')], max_length=10)),
                ('numero_documento', models.CharField(blank=True, max_length=20)),
                ('nacionalidad', models.CharField(blank=True, max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('m', 'Masculino'), ('f', 'Femenino')], max_length=1)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('ubigeo_codigo', models.CharField(blank=True, max_length=6)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('distrito', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('numero_documento', ''), _negated=True), fields=('tipo_documento', 'numero_documento'), name='unique_tipo_numero_documento_non_blank')],
            },
        ),
    ]
