# Generated by Django 6.0.7 on 2026-08-10 20:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('cv', models.FileField(upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('rechazado', 'Rechazado'), ('aprobado', 'Aprobado')], default='pendiente', max_length=10)),
                ('resultado_filtro', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='recruiting.puesto')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
