# Generated by Django 6.0.7 on 2026-08-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0004_seed_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='funciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='puesto',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], default='presencial', max_length=10),
        ),
        migrations.AddField(
            model_name='puesto',
            name='requisitos_deseables',
            field=models.TextField(blank=True),
        ),
    ]
