# Generated by Django 6.0.7 on 2026-08-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0005_puesto_funciones_puesto_modalidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='vacantes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
