# Generated by Django 6.0.7 on 2026-08-24 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0006_puesto_vacantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='vacantes',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
