# Generated by Django 6.0.7 on 2026-08-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0007_alter_puesto_vacantes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='postulacion',
            constraint=models.UniqueConstraint(fields=('puesto', 'email'), name='unique_puesto_email'),
        ),
    ]
