# Generated by Django 6.0.7 on 2026-08-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0008_postulacion_unique_puesto_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='fecha_limite_entrevista',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
