# Generated by Django 6.0.7 on 2026-08-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0009_postulacion_fecha_limite_entrevista'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='limite_postulaciones',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
